server:
  port: 8081
springdoc:
  swagger-ui:
    path: /swagger.html # swagger custom path
    enabled: true  # Disabling the swagger-ui production enviroments always false
  packagesToScan: com.prueba.reservas.cmd.api.controllers, com.prueba.reservas.cmd.api.command
  pathsToMatch: /v1, /**
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hotelreservations
      username: jcallejo
      password: Jcallejo2023$
      authentication-database: admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: "hotel_availability_searches" 
    
     